### ISSUE TITLE
Returned error has message "The operation was completed successfully".

### ISSUE THREAD

**Issue by frontierpsycho** [hectane/go-acl#1]
I'm trying to use this library, and even though it properly reports than an error has occurred, when printing that error with `%v`, I get the message: "The operation completed successfully." Is it possible to get a message that corresponds to the error, as seen on [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx) list?

**Comment by nathan-osman** [comment]
If I recall correctly, this bug is caused by the way `golang.org/x/sys/windows` deals with errors. I'll take a closer look and see if this is something go-acl can fix or work around.

**Comment by nathan-osman** [comment]
I traced this back to the `syscall` package in the Go standard library. There doesn't seem to be much I can do about it unfortunately. I may file a bug later and see if someone from the Go team can figure out what's going on.

**Comment by frontierpsycho** [comment]
Thanks! I guess we can close this for now, then.

**Comment by JohnMaguire** [comment]
Did you file this bug upstream? Curious if there was any movement towards getting this fixed.

**Comment by andydotxyz** [comment]
I don't know if it helps but I just encountered this and found that on windows `syscall.Syscall` does not return a true `nil` on success, but instead `syscall.Errno(0)` - almost the same but not quite...
