### ISSUE TITLE
Unable to delete file after Chmod(file, 07xx)

### ISSUE THREAD

**Issue by zb140** [hectane/go-acl#11]
After changing the acl for a file with `Chmod(file, 07xy)`, I am unable to delete the file.  This happens because none of the generic read, write, or execute rights include `DELETE` permission (https://docs.microsoft.com/en-us/windows/desktop/FileIO/file-security-and-access-rights).

I know on Unix systems delete permission is controlled by the parent directory rather than the file itself, so the analogy doesn't work 100%, but I would expect to be able to delete files if I can also write them.

Can we change `Chmod` to add `DELETE` if the write bit is set?  I can submit a PR if this is a change you would accept.

**Comment by nathan-osman** [comment]
Good catch!

Sure, if you submit a PR, I'll gladly accept and merge.
